<<<<<<< HEAD
function api_call(a,b,c){a.open("POST",api_url);a.setRequestHeader("Content-Type","application/json");a.withCredentials=!0;a.onreadystatechange=c;a.send(JSON.stringify(b))}function api_response(a){if(4==a.readyState)if(200==a.status)if(a=JSON.parse(a.responseText),void 0!=a.login)top.location.href=login_url;else return a;else document.location+="";return!1}
function hookEvent(a,b,c){"string"==typeof a&&(a=document.getElementById(a));null!=a&&(a.addEventListener?("mousewheel"==b&&a.addEventListener("DOMMouseScroll",c,!1),a.addEventListener(b,c,!1)):a.attachEvent&&a.attachEvent("on"+b,c))}function cancelEvent(a){a=a?a:window.event;a.stopPropagation&&a.stopPropagation();a.preventDefault&&a.preventDefault();a.cancelBubble=!0;a.cancel=!0;return a.returnValue=!1}
if("undefined"==typeof KeyEvent)var KeyEvent={DOM_VK_SPACE:32,DOM_VK_PAGE_UP:33,DOM_VK_PAGE_DOWN:34,DOM_VK_LEFT:37,DOM_VK_UP:38,DOM_VK_RIGHT:39,DOM_VK_DOWN:40,DOM_VK_A:65,DOM_VK_D:68,DOM_VK_R:82,DOM_VK_S:83,DOM_VK_W:87,DOM_VK_NUMPAD2:98,DOM_VK_NUMPAD4:100,DOM_VK_NUMPAD5:101,DOM_VK_NUMPAD6:102,DOM_VK_NUMPAD8:104};var dispatch_xhr=void 0,pcnt=0,load_cooldown=!1,load_queued=void 0,holdingOverrideKey=!1;
function load_image_dispatch(){var a=api_response(dispatch_xhr);0!=a&&(void 0!=a.error?document.location+="":(history.replaceState({page:a.p,imgkey:a.k,json:a,expire:get_unixtime()+300},document.title,base_url+a.s),apply_json_state(a)),dispatch_xhr=void 0)}
function apply_json_state(a){window.scrollTo(0,0);document.getElementById("i1").style.width=a.x+"px";document.getElementById("i2").innerHTML=a.n+a.i;document.getElementById("i3").innerHTML=a.i3;document.getElementById("i4").innerHTML=a.i+a.n;document.getElementById("i5").innerHTML=a.i5;document.getElementById("i6").innerHTML=a.i6;si=parseInt(a.si);xres=parseInt(a.x);yres=parseInt(a.y);update_window_extents()}function load_image(a,b){return _load_image(a,b,!1)}
function _load_image(a,b,c){if(holdingOverrideKey)return!0;var d=base_url+("s/"+b+"/"+gid+"-"+a);if(c)--pcnt;else{if(load_cooldown)return!1;++pcnt}if(history.pushState&&pcnt<=prl){if(void 0!=dispatch_xhr)return!1;c||(load_cooldown=!0,setTimeout(function(){load_cooldown=!1},1E3));dispatch_xhr=new XMLHttpRequest;api_call(dispatch_xhr,{method:"showpage",gid,page:a,imgkey:b,showkey},function(){load_image_dispatch()});c||history.pushState({page:a,imgkey:b},document.title,d)}else pcnt=0,document.location=
d;return!1}function get_ypos(){return Math.max(window.pageYOffset?window.pageYOffset:0,document.documentElement?document.documentElement.scrollTop:0,document.body?document.body.scrollTop:0)}function scroll_space(a){var b=get_ypos();window.scrollBy(0,Math.round(.75*window.innerHeight*(a?-1:1)));if(!a&&b==get_ypos())document.getElementById("next").onclick()}function get_unixtime(){return Math.round((new Date).getTime()/1E3)}
function update_window_extents(){var a=Math.max(480,window.innerWidth-20),b=xres,c=yres;b>a&&(c=Math.round(c*a/b),b=a);a=document.getElementById("img");var d=document.getElementById("i1");a.style.width=b+"px";a.style.height=c+"px";d.style.width=b+"px"}function nl(a){document.location+=(-1<(document.location+"").indexOf("?")?"&":"?")+"nl="+a;return!1}
window.onpopstate=function(a){void 0!=a.state&&("undefined"!=typeof a.state.json&&a.state.expire>get_unixtime()?apply_json_state(a.state.json):_load_image(a.state.page,a.state.imgkey,!0))};window.onresize=update_window_extents;setTimeout(function(){update_window_extents()},50);history.replaceState&&setTimeout(function(){history.replaceState({page:startpage,imgkey:startkey},document.title,document.location)},50);
document.onkeydown=function(a){if(a.altKey||a.ctrlKey||a.metaKey)holdingOverrideKey=!0;else{var b=window.event?a.keyCode:a.which;if(a.shiftKey)switch(b){case KeyEvent.DOM_VK_SPACE:scroll_space(!0),cancelEvent(a)}else switch(b){case KeyEvent.DOM_VK_RIGHT:case KeyEvent.DOM_VK_D:case KeyEvent.DOM_VK_NUMPAD6:document.getElementById("next").onclick();cancelEvent(a);break;case KeyEvent.DOM_VK_LEFT:case KeyEvent.DOM_VK_A:case KeyEvent.DOM_VK_NUMPAD4:document.getElementById("prev").onclick();cancelEvent(a);
break;case KeyEvent.DOM_VK_W:case KeyEvent.DOM_VK_NUMPAD8:window.scrollBy(0,-50);cancelEvent(a);break;case KeyEvent.DOM_VK_S:case KeyEvent.DOM_VK_NUMPAD2:window.scrollBy(0,50);cancelEvent(a);break;case KeyEvent.DOM_VK_SPACE:scroll_space(!1);cancelEvent(a);break;case KeyEvent.DOM_VK_R:case KeyEvent.DOM_VK_NUMPAD5:document.getElementById("loadfail").onclick(),cancelEvent(a)}}};document.onkeyup=function(a){holdingOverrideKey=!1};
=======
function api_call(a,b,c){a.open("POST",api_url);a.setRequestHeader("Content-Type","application/json");a.withCredentials=!0;a.onreadystatechange=c;a.send(JSON.stringify(b))}function api_response(a){if(4==a.readyState)if(200==a.status)if(a=JSON.parse(a.responseText),void 0!=a.login)top.location.href=login_url;else return a;else document.location+="";return!1}
function hookEvent(a,b,c){"string"==typeof a&&(a=document.getElementById(a));null!=a&&(a.addEventListener?("mousewheel"==b&&a.addEventListener("DOMMouseScroll",c,!1),a.addEventListener(b,c,!1)):a.attachEvent&&a.attachEvent("on"+b,c))}function cancelEvent(a){a=a?a:window.event;a.stopPropagation&&a.stopPropagation();a.preventDefault&&a.preventDefault();a.cancelBubble=!0;a.cancel=!0;return a.returnValue=!1}
if("undefined"==typeof KeyEvent)var KeyEvent={DOM_VK_SPACE:32,DOM_VK_PAGE_UP:33,DOM_VK_PAGE_DOWN:34,DOM_VK_LEFT:37,DOM_VK_UP:38,DOM_VK_RIGHT:39,DOM_VK_DOWN:40,DOM_VK_A:65,DOM_VK_D:68,DOM_VK_R:82,DOM_VK_S:83,DOM_VK_W:87,DOM_VK_NUMPAD2:98,DOM_VK_NUMPAD4:100,DOM_VK_NUMPAD5:101,DOM_VK_NUMPAD6:102,DOM_VK_NUMPAD8:104};var dispatch_xhr=void 0,pcnt=0,load_cooldown=!1,load_queued=void 0,holdingOverrideKey=!1;
function load_image_dispatch(){var a=api_response(dispatch_xhr);0!=a&&(void 0!=a.error?document.location+="":(history.replaceState({page:a.p,imgkey:a.k,json:a,expire:get_unixtime()+300},document.title,base_url+a.s),apply_json_state(a)),dispatch_xhr=void 0)}
function apply_json_state(a){window.scrollTo(0,0);document.getElementById("i1").style.width=a.x+"px";document.getElementById("i2").innerHTML=a.n+a.i;document.getElementById("i3").innerHTML=a.i3;document.getElementById("i4").innerHTML=a.i+a.n;document.getElementById("i5").innerHTML=a.i5;document.getElementById("i6").innerHTML=a.i6;si=parseInt(a.si);xres=parseInt(a.x);yres=parseInt(a.y);update_window_extents()}function load_image(a,b){return _load_image(a,b,!1)}
function _load_image(a,b,c){if(holdingOverrideKey)return!0;var d=base_url+("s/"+b+"/"+gid+"-"+a);if(c)--pcnt;else{if(load_cooldown)return!1;++pcnt}if(history.pushState&&pcnt<=prl){if(void 0!=dispatch_xhr)return!1;c||(load_cooldown=!0,setTimeout(function(){load_cooldown=!1},1E3));dispatch_xhr=new XMLHttpRequest;api_call(dispatch_xhr,{method:"showpage",gid,page:a,imgkey:b,showkey},function(){load_image_dispatch()});c||history.pushState({page:a,imgkey:b},document.title,d)}else pcnt=0,document.location=
d;return!1}function get_ypos(){return Math.max(window.pageYOffset?window.pageYOffset:0,document.documentElement?document.documentElement.scrollTop:0,document.body?document.body.scrollTop:0)}function scroll_space(a){var b=get_ypos();window.scrollBy(0,Math.round(.75*window.innerHeight*(a?-1:1)));if(!a&&b==get_ypos())document.getElementById("next").onclick()}function get_unixtime(){return Math.round((new Date).getTime()/1E3)}
function update_window_extents(){var a=Math.max(480,window.innerWidth-20),b=xres,c=yres;b>a&&(c=Math.round(c*a/b),b=a);a=document.getElementById("img");var d=document.getElementById("i1");a.style.width=b+"px";a.style.height=c+"px";d.style.width=b+"px"}function nl(a){document.location+=(-1<(document.location+"").indexOf("?")?"&":"?")+"nl="+a;return!1}
window.onpopstate=function(a){void 0!=a.state&&("undefined"!=typeof a.state.json&&a.state.expire>get_unixtime()?apply_json_state(a.state.json):_load_image(a.state.page,a.state.imgkey,!0))};window.onresize=update_window_extents;setTimeout(function(){update_window_extents()},50);history.replaceState&&setTimeout(function(){history.replaceState({page:startpage,imgkey:startkey},document.title,document.location)},50);
document.onkeydown=function(a){if(a.altKey||a.ctrlKey||a.metaKey)holdingOverrideKey=!0;else{var b=window.event?a.keyCode:a.which;if(a.shiftKey)switch(b){case KeyEvent.DOM_VK_SPACE:scroll_space(!0),cancelEvent(a)}else switch(b){case KeyEvent.DOM_VK_RIGHT:case KeyEvent.DOM_VK_D:case KeyEvent.DOM_VK_NUMPAD6:document.getElementById("next").onclick();cancelEvent(a);break;case KeyEvent.DOM_VK_LEFT:case KeyEvent.DOM_VK_A:case KeyEvent.DOM_VK_NUMPAD4:document.getElementById("prev").onclick();cancelEvent(a);
break;case KeyEvent.DOM_VK_W:case KeyEvent.DOM_VK_NUMPAD8:window.scrollBy(0,-50);cancelEvent(a);break;case KeyEvent.DOM_VK_S:case KeyEvent.DOM_VK_NUMPAD2:window.scrollBy(0,50);cancelEvent(a);break;case KeyEvent.DOM_VK_SPACE:scroll_space(!1);cancelEvent(a);break;case KeyEvent.DOM_VK_R:case KeyEvent.DOM_VK_NUMPAD5:document.getElementById("loadfail").onclick(),cancelEvent(a)}}};document.onkeyup=function(a){holdingOverrideKey=!1};
>>>>>>> 572b7d1 (第一次提交)
